
import {
  Loader2,
  LogIn,
  User,
  Mail,
  Lock,
  LayoutDashboard,
  Settings,
  LogOut,
  Home,
  ChevronRight,
  MessageSquare,
  HelpCircle,
  FileText,
  AlertCircle,
  Check,
  X,
  RefreshCw,
  ChevronLeft,
  Menu,
  Plus,
  Droplets,
  Zap
} from "lucide-react";

export const Icons = {
  logo: LayoutDashboard,
  login: LogIn,
  user: User,
  mail: Mail,
  lock: Lock,
  dashboard: LayoutDashboard,
  settings: Settings,
  logout: LogOut,
  home: Home,
  chevronRight: ChevronRight,
  message: MessageSquare,
  help: HelpCircle,
  file: FileText,
  spinner: Loader2,
  alert: AlertCircle,
  check: Check,
  close: X,
  refresh: RefreshCw,
  back: ChevronLeft,
  menu: Menu,
  add: Plus,
  water: Droplets,
  electricity: Zap
};
