// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uestvkycssqdrxaxggaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlc3R2a3ljc3NxZHJ4YXhnZ2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTk4MjgsImV4cCI6MjA2MDg5NTgyOH0.u4xl-IzfzS5OPRMUzM1tK3_1gB-E-9TQvncYMI6YVKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);